//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelReservation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Booking()
        {
            this.Guests = new HashSet<Guest>();
        }
    
        public int BookingID { get; set; }
        public Nullable<int> RoomIDFK { get; set; }
        public string BookingDate { get; set; }
        public string BookingFrom { get; set; }
        public string BookingTo { get; set; }
        public string NumOfGuests { get; set; }
        public string RoomBooked { get; set; }
        public string CheckedIn { get; set; }
        public string CheckedOut { get; set; }
        public string RoomCost { get; set; }
    
        public virtual Room Room { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Guest> Guests { get; set; }
    }
}
